# SPDX-FileCopyrightText: 2026 HarryLoong
# SPDX-License-Identifier: MIT

[Addon]
Name=Qwen Voice Input
Name[zh_CN]=Qwen 语音输入
Comment=Commit Qwen Voice Input text through fcitx
Comment[zh_CN]=通过 fcitx 提交 Qwen 语音输入文本
Category=Module
Version=0.2.0
Library=libqwenvoiceinput
Type=SharedLibrary
OnDemand=False
Configurable=False

[Addon/Dependencies]
0=core:5.1.0
