# SPDX-FileCopyrightText: 2026 HarryLoong
# SPDX-License-Identifier: MIT

[Addon]
Name=VoxKey
Name[zh_CN]=简听输入
Comment=Commit VoxKey text through fcitx
Comment[zh_CN]=通过 fcitx 提交简听输入文本
Category=Module
Version=0.2.0
Library=libvoxkeyinput
Type=SharedLibrary
OnDemand=False
Configurable=False

[Addon/Dependencies]
0=core:5.1.0
